-- SQL Schema for SMK Prima Unggul Smart School Hub

-- 1. Exam Results Table
CREATE TABLE exam_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    user_name TEXT NOT NULL,
    user_major TEXT,
    nisn TEXT,
    score DECIMAL NOT NULL,
    is_passed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Student Attendance Table
CREATE TABLE student_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL, -- or UUID if using Supabase Auth for students
    teacher_id UUID,
    student_name TEXT NOT NULL,
    nis TEXT,
    class_name TEXT,
    major_name TEXT,
    status TEXT NOT NULL, -- hadir, sakit, izin, alpha
    date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Staff Attendance Table
CREATE TABLE staff_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID NOT NULL,
    display_name TEXT,
    role TEXT,
    status TEXT NOT NULL,
    date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Student Profiles (Optional if not using auth for each student)
CREATE TABLE students (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    nis TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    class TEXT NOT NULL,
    major TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS (Row Level Security)
ALTER TABLE exam_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;

-- 5. Policies
-- Exam Results: Anyone authenticated can read, only users can insert their own
CREATE POLICY "Allow authenticated users to read exam results" ON exam_results FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow users to insert their own results" ON exam_results FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- Student Attendance: Admin and Teachers can read/write
CREATE POLICY "Allow teachers and admins to manage student attendance" ON student_attendance FOR ALL TO authenticated USING (true);

-- Staff Attendance: Users can read/write their own
CREATE POLICY "Users can manage their own staff attendance" ON staff_attendance FOR ALL TO authenticated USING (auth.uid() = uid);
